### ISSUE TITLE
Changes in how cirq handles results.data

### ISSUE THREAD

**Issue by HehnLukas** [MafaldaRA/VQE#1]
Hi,
I don't know if you still care about this project, given that it seems you have finished your masters (congrats!). If you don't care about keeping it up to date, that is perfectly reasonable, but do still please let me know how I can cite this if I end up publishing anything based on this.

If you would like to keep things up to date, I've found the following bug in CIRQ_UCCSD_VQE.ipynb:

Using the newest versions of OF and cirq, a KeyError occurs in the measureString function, which I believe is caused because cirq no longer saves the columns from identity Paulis in the results.data after this section:
```
if (pauliString != "I"*len(qubits)):
    s = cirq.Simulator()
    results = s.run(circuit,repetitions = repetitions)
```

It can be fixed by changing the for loop over range(repetitions) to the following:

```
for j in range(repetitions):
        meas = 1
        non_identities = 0
        for i in range(len(qubits)):
            if (pauliString[i] != "I"):
              
              meas = meas*(1-2*np.array(results.data)[j][non_identities]) # was meas = meas*(1-2*results.data[i][j]), but that failed. I guess Cirq changed how they save results.data
              non_identities += 1 # This was not here, but is necessary because Cirq no longer adds identity matrices to the results.data
        total += meas
```

Again, you are obviously under no obligation to keep this up to date, and I would love to credit you properly because this has been a great starting point for me in OF and Cirq, so really the main reason I'm posting this is so I can cite this in the future.

**Comment by mafaldaramoa** [comment]
Hello,

I have indeed finished my masters, but I'm still interested in this and I appreciate the help keeping the code up to date. 

About the error: I believe that since results.data is a Pandas DataFrame, it is easy to access data for a given qubit by using the corresponding column label, regardless of there being or not columns for qubits acted on by identity operators. I have changed the code to use `str(i)` rather than `i` as the key and I think that's enough to solve the problem.

Regarding the citation, my dissertation will eventually be available online - when that happens, I'll update the ReadMe with the access information. Until then, you can cite this GitHub Repository.

Thanks for the interest, I am glad to know this has been helpful. 

All the best for your work!

**Comment by mafaldaramoa** [comment]
Hello again @HehnLukas,

I wanted to let you know that I've made my thesis available on arXiv: https://arxiv.org/abs/2212.04323
